### ISSUE TITLE
Support for inserting new lines?

### ISSUE THREAD

**Issue by Bartlomiejsz** [Siilwyn/css-declaration-sorter#163]
Hi!
I'm wondering, if there are any plans to allow reorder function to insert empty line between some styles group?

Best regards

**Comment by Siilwyn** [comment]
:wave: hey sorry for the late reply, I don't have any plans for this. Do you think this would be useful? Most selectors I write have a handful of properties so there would be a lot of newlines which doesn't aid readability.

**Comment by Bartlomiejsz** [comment]
Hi @Siilwyn, thank you for answer.
Yes, I guess so, whole point of ordering styles in some way is to make it more readable, and I believe splitting those to some particular groups makes it even better.
I was trying to achieve https://css-tricks.com/poll-results-how-do-you-order-your-css-properties/ specifically

**Comment by Siilwyn** [comment]
Hey sorry for not responding, I'm not sure what to do with this issue yet. I don't agree since it can decrease readability for selectors that have only one or two selectors in each group. However if more people feel like this should be an option it might be worth considering, it does add significant complexity to the code that's why I'm hesitant.
