### ISSUE TITLE
Prefixed vendor rules

### ISSUE THREAD

**Issue by leepowellcouk** [Siilwyn/css-declaration-sorter#36]
Would it be possible to keep prefixed vendor rules along with their non-prefixed siblings? Currently they get moved to the top of the block.

**Comment by Siilwyn** [comment]
Interesting question, what is the use case?

In my mind vendor rules are in the build output but you're sorting your source code.

**Comment by leepowellcouk** [comment]
We have a legacy application with no build process (long story), so are having to add the vendor prefixes manually. So in our case, they are part of the source code :(

**Comment by Siilwyn** [comment]
Not sure if this edge-case justifies adding this feature with it's complexity to this module, especially since this is a 'build tool' so a build process is expected. As a workaround to use now you could copy the [order JSON](https://github.com/Siilwyn/css-declaration-sorter/tree/master/orders) and add vendor prefixes there using the custom order option.
