### ISSUE TITLE
SMACSS ordering update

### ISSUE THREAD

**Issue by generator85** [Siilwyn/css-declaration-sorter#41]
It would be great if the order for SMACSS could be made inline with the list that Stylelint uses (https://github.com/cahamilton/css-property-sort-order-smacss/blob/master/index.js). This same ordering is also used by SCSS-Lint.

I know that their isn't an official list available, but I guess if more packages use the same ordering a standard will be automatically created. Currently a lot of properties in the SMACSS ordering of this package are ordered alphabetically.

For people that don't lint their CSS this change wouldn't really make any difference.

**Comment by Siilwyn** [comment]
Thanks for reporting!

To clarify do you use a linter that checks the order besides ordering automatically? That seems like double work.

Sadly the order can't be fully aligned since this package contains more properties which are not present in Stylelint. Also worth mentioning is that the order used in this package has been viewed and approved by their author.

Think it is worth investigating the differences and move properties where logical, such as the `z-index` you mentioned going from 'Other' to 'Box'.

Thoughts? :thought_balloon:

**Comment by Siilwyn** [comment]
I found several properties and moved them to the category as in Stylelint. If you find more, I would be happy to hear.

**Comment by generator85** [comment]
Hi Sillwyn, thanks I'll let you know if I find more!
